### PR TITLE
the output of c implementation changed by sarrac issue 141

### PR DESCRIPTION
**Pull request by petersilva**
output of C implementation changes, implemented in:
https://github.com/MetPX/sarrac/pull/144

to fix: 
https://github.com/MetPX/sarrac/issues/141

so both pulls should be merged at the same time (probably sr_insects first, then sarrac)

### CODE REVIEW

**Review by andreleblanc11 — COMMENTED** [review]
I think you may have missed some instances of the log changes? Like on line 371 of `flakey_broker/flow_include.sh`?

**Comment by petersilva** [comment]
second reading... no... line 371 is for guarded by an if statement that refers to older versions of sarrac, so it must not be modified.  It is correct as is.

**Comment by andreleblanc11** [comment]
That makes sense. Wouldn't that mean though that changes on `restart_server/flow_include.sh` at line 364 shouldn't be changed? Same thing for `static_flow/flow_include.sh` line 357?

**Comment by petersilva** [comment]
Since the C thing was merged, this needs to be merged... but when... it will break all the flow tests until the C patches are released...

**Comment by petersilva** [comment]
@andreleblanc11 yup... good catch. patch inbound.

**Pull request merged**
